In [3]:
import os
import shutil

source = r"C:\Users\Admin\PyCharmMiscProject\E-Commerce-data-pipeline\data\cleaned_sales.csv"
destination = r"C:\Users\Admin\PyCharmMiscProject\ecommerce-sales-eda\data\cleaned_sales.csv"

# Automatically creates the 'data' directory if missing
os.makedirs(os.path.dirname(destination), exist_ok=True)

# Copy file
shutil.copy(source, destination)
print("File copied successfully!")

File copied successfully!

In [4]:
import pandas as pd

df = pd.read_csv("data/cleaned_sales.csv")
df.head()

,order_id,customer_name,date,gender,email,phone_number,category,price,quantity,customer_rating,month,sales
0,ORD-00001,Mercedes Sim,06/03/2026,-,mercedes.sim83@yahoo.com,(702) 995-8622,Not Known,9.38,2,2.5,June,18.76
1,ORD-00002,Aaron Portelli,06/03/2026,Male,aaron.portelli23@yahoo.com,(571) 960-4868,Home,465.25,4,4.2,June,1861.00
2,ORD-00003,Dalia Dijoux,06/04/2026,Female,dalia.dijoux49@hotmail.com,(304) 839-3706,Toys,242.50,7,3.6,June,1697.50
3,ORD-00004,Leonie Ramdin,06/04/2026,-,Invalid email,(401) 512-4558,Grocery,483.37,4,2.9,June,1933.48
4,ORD-00005,Unkown Unkown,06/04/2026,-,zahra.oliver91@outlook.com,(217) 946-9396,Beauty,242.50,5,3.7,June,1212.50

In [5]:
df.info()
df.describe().round(2)

<class 'pandas.DataFrame'>
RangeIndex: 441 entries, 0 to 440
Data columns (total 12 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   order_id         441 non-null    str
 1   customer_name    441 non-null    str
 2   date             441 non-null    str
 3   gender           441 non-null    str
 4   email            441 non-null    str
 5   phone_number     441 non-null    str
 6   category         441 non-null    str
 7   price            441 non-null    float64
 8   quantity         441 non-null    int64
 9   customer_rating  441 non-null    float64
 10  month            441 non-null    str
 11  sales            441 non-null    float64
dtypes: float64(3), int64(1), str(8)
memory usage: 41.5 KB

        price  quantity  customer_rating     sales
count  441.00    441.00           441.00    441.00
mean   245.00      6.09             2.89   1516.53
std    143.12      8.20             1.33   2704.70
min      5.03      1.00             0.00     11.22
25%    118.06      3.00             2.00    484.64
50%    242.50      5.00             2.80   1038.94
75%    364.54      8.00             3.70   1940.00
max    499.70    100.00            10.00  39376.00